remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Anish Khairnar - Data Analytics Portfolio
description: Data Science projects

# Optional settings
show_downloads: false
